
services:
    # Define the "app" service, which will run your application.
    app:
        # Specify how to build the app service using a Dockerfile.
        # The "context" defines the directory where the Dockerfile is located (in this case, the "app" folder).
        build:
            context: app
        # Map the container's port 5000 to the same port on the host machine.
        # This allows you to access the application on port 5000 from your host.
        ports:
            - "5000"

    # Define the "nginx" service, which will act as a reverse proxy for your application.
    nginx:
        # Use the latest NGINX image available from Docker Hub.
        image: nginx:latest
        # Mount a local Nginx configuration file into the container.
        # The file `nginx.conf` is mapped to the container's `/etc/nginx/nginx.conf` in read-only mode (`:ro`).
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        # Specify that the "nginx" service depends on the "app" service.
        # This ensures the "app" service starts first before NGINX is started.
        depends_on:
            - app
        # Map port 80 on the container to port 80 on the host machine.
        # This allows access to the NGINX server from the host via standard HTTP (port 80).
        ports:
            - "80:80"